
# werkt niet met verplaatste bundle, subclass maken in UserBundle
#RequestCounts:
#    path:      /guard/show/{username}
#    defaults:  { _controller: AuthenticationGuardBundle:RequestCounts:show }

Guard:
    resource: "@MetaclassAuthenticationGuardBundle/Controller/GuardStatsController.php"
    type:     annotation
    prefix:   /guard
