# Web based wser interface for user administators to look into why a user may have been blocked
#
# WARNING: if you just add this yml as a resource to your routing.yml configuration,
# you need to confige your access control to require authentication and administrative rights,
# otherwise anybody will be able to see the user names, ip addresses, date, time and more
# of all login attemtps!!!
#
Guard_statistics:
    path: /statistics
    defaults:  { _controller: "%metaclass_auth_guard.ui.statistics.controller%:statistics" }

Guard_history:
    path: /history/{ipAddress}
    defaults: { _controller: "%metaclass_auth_guard.ui.statistics.controller%:history" }
    requirements:
        ipAddress: "[^/]+"

Guard_statisticsByUserName:
    path: /statistics/{username}
    defaults:  { _controller: "%metaclass_auth_guard.ui.statistics.controller%:statisticsByUserName" }
    requirements:
        username: "[^/]*"
