parameters:
    metaclass_auth_guard.manager.class: "Metaclass\\TresholdsGovernor\\Manager\\RdbManager"
    metaclass_auth_guard.gateway.class: "Metaclass\\TresholdsGovernor\\Gateway\\RdbGateway"
    metaclass_auth_guard.tresholds_governor.class: "Metaclass\\TresholdsGovernor\\Service\\TresholdsGovernor"
    metaclass_auth_guard.authentication.listener.form.class: "Metaclass\\AuthenticationGuardBundle\\Service\\UsernamePasswordFormAuthenticationGuard"

    metaclass_auth_guard.ui.statistics.controller: "MetaclassAuthenticationGuardBundle:GuardStats"
    metaclass_auth_guard.ui.StatsPeriod.formType: "Metaclass\\AuthenticationGuardBundle\\Form\\Type\\StatsPeriodType"

services:

# Entity Manager for Request Counters
    metaclass_auth_guard.connection_login:
        class: Doctrine\DBAL\Connection
        factory: ["@doctrine", getConnection]
        arguments: [%metaclass_auth_guard.db_connection.name%]

    metaclass_auth_guard.gateway:
        class: %metaclass_auth_guard.gateway.class%
        arguments: ["@metaclass_auth_guard.connection_login"]

    metaclass_auth_guard.manager:
        class: %metaclass_auth_guard.manager.class%
        arguments: ["@metaclass_auth_guard.gateway"]

    metaclass_auth_guard.tresholds_governor:
        class: %metaclass_auth_guard.tresholds_governor.class%
        arguments: [%metaclass_auth_guard.tresholds_governor_params%, "@metaclass_auth_guard.manager"]
