parameters:
    metaclass_auth_guard.manager_requestcounts.class: "Metaclass\TresholdsGovernor\Manager\RdbManager"
    metaclass_auth_guard.tresholds_governor.class: "Metaclass\TresholdsGovernor\Service\TresholdsGovernor"
    metaclass_auth_guard.authentication.listener.form.class: Metaclass\AuthenticationGuardBundle\Service\UsernamePasswordFormAuthenticationGuard

services:

# Entity Manager for Request Counters
    metaclass_auth_guard.connection_login:
        factory_service: doctrine
        factory_method: getConnection
        class: Doctrine\DBAL\Connection
        public: false
        arguments: [%metaclass_auth_guard.db_connection.name%] 

    metaclass_auth_guard.tresholds_governor:
        class: %metaclass_auth_guard.tresholds_governor.class%
        arguments: ["@metaclass_auth_guard.connection_login", %metaclass_auth_guard.manager_requestcounts.class%, %metaclass_auth_guard.tresholds_governor_params%]




